server.port=8081
spring.application.name=app-native

# Virtual Threads DESABILITADAS
spring.threads.virtual.enabled=false

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=app-native
management.metrics.tags.runtime=graalvm-native
management.metrics.tags.virtual_threads=false
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.90,0.95,0.99
