server.port=8080
spring.application.name=app-jvm

# Virtual Threads HABILITADAS
spring.threads.virtual.enabled=true

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.tags.application=app-jvm
management.metrics.tags.runtime=hotspot-jit
management.metrics.tags.virtual_threads=true
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.metrics.distribution.percentiles.http.server.requests=0.5,0.90,0.95,0.99
